#!/usr/bin/env python3

import subprocess
from sys import stderr, exit

tests = [
    [ 0,   '', ''],
    [ 0.1, 'eval "expr that is discarded"', ''],
    [ 0.2, 'eval nil', ''],
    [ 0.3, 'eval "anything"', ''],
    [ 1, 'var a; print not a', 'true'],
    [ 2, 'var a; print a==nil', 'true'],
    [ 3, 'var a=1; eval a=nil; print a==nil', 'true'],
    [ 4, 'print 1+1', '2'],
    [ 5, 'print 1+2.14', '3.14'],
    [ 6,   'print 123/2-50+2*8',       '27'],
    [ 6.1, 'print 123.0/2-50+2*8',   '27.5'],
    [ 6.2, 'print 123/2.0-50+2*8',   '27.5'],
    [ 6.3, 'print 123.0/2.0-50+2*8', '27.5'],
    [ 6.4, 'print 123/2-50+2.0*8',   '27'],
    [ 6.5, 'print 123/2-50+2*8.0',   '27'],
    [ 6.6, 'print 123/2-50+2.0*8.0', '27'],
    [ 6.7, 'print 123/2-50.0+2*8',   '27'],
    [ 7, 'print 1-2', '-1'],
    [ 8, 'print 1--2', '3'],
    [ 9, 'print 1- +1', '0'],
    [10,   'print 1+ +1',     '2'],
    [10.1, 'print 1.0+ +1',   '2'],
    [10.2, 'print 1+ +1.0',   '2'],
    [10.3, 'print 1.0+ +1.0', '2'],
    [11,   'print ---10',   '-10'],
    [11.1, 'print ---10.0', '-10'],
    [12,   'print 1==1',     'true'],
    [12.1, 'print 1.0==1',   'true'],
    [12.2, 'print 1==1.0',   'true'],
    [12.3, 'print 1.0==1.0', 'true'],
    [13,   'print not 1>3',     'true'],
    [13.1, 'print not 1.0>3',   'true'],
    [13.2, 'print not 1>3.0',   'true'],
    [13.3, 'print not 1.0>3.0', 'true'],
    [13.4, 'print not 3<=1',    'true'],
    [14,   'print 1<2 and 0 or "whatever"',     '0'],
    [14.1, 'print 1.0<2 and 0 or "whatever"',   '0'],
    [14.2, 'print 1<2.0 and 0 or "whatever"',   '0'],
    [14.3, 'print 1.0<2.0 and 0 or "whatever"', '0'],
    [15,   'print 1>2 or true and 42', '42'],
    [16,   'print 1<10/5 and 127*-1+154', '27'],
    [17, 'print "q"*2', 'qq'],
    [18, 'print "q"+"x"', 'qx'],
    [19, 'print "q"+3', 'q3'],
    [20, 'print "q"+3.14', 'q3.14'],
    [21, 'print "q"=="q"', 'true'],
    [22, 'print "q"!="p"', 'true'],
    [23, 'print "p"<"q"',  'true'],
    [24, 'print "q">"p"',  'true'],
    [25,   'print not (false or true)',  'false'],
    [25.1, 'print not (false and true)', 'true'],
    [25.2, 'print "" or 42',       '42'],
    [26, 'var a=100; var b=a-90; print -b', '-10'],
    [27, 'var a=1; var b=2; print a+b',  '3'],
    [28, 'var a=1; eval a=a+1; print a', '2'],
    [29, 'var a=1; print a=a+1',         '2'],
    [30, 'def blk {print TYPE}',         'blk'],
    [31, 'def blk "foo" {print TYPE+"."+NAME}', 'blk.foo'],
    [32, 'var a=1; def blk {print TYPE}',   'blk'],
    [33, 'print 1; def blk {print TYPE}',   '1\nblk'],
    [34, 'var a=1; def blk {print TYPE+a}', 'blk1'],
    [35, 'def blk {var a=1; print TYPE+a}', 'blk1'],
    [36, 'var x=1; def blk {var a=1+x; print TYPE+a}',   'blk2'],
    [37, 'def blk {var a=1; var b=2; print TYPE+(a+b)}', 'blk3'],
    [38, 'var x=5; def blk {var a=1; var b=2; print TYPE+(a+b+x)}', 'blk8'],
    [39, 'def b1{var x=1; def b2 {var a=2; print TYPE+(a+x)}}',     'b23'],
    [40, 'var a=5; def blk {var a=a+1; print TYPE+a}',   'blk6'],
    [41, 'def b1{var a=5; def b2 {var a=a+1; print TYPE+a} print TYPE+a}', 'b26\nb15'],
    [42, 'def b1{var a=5; def b2 {eval a=a+1; print TYPE+a} print TYPE+a}','b26\nb16'],
    [43, 'def b1{ print TYPE; def b2{print TYPE} }; def b3{print TYPE}', 'b1\nb2\nb3'],
    [44, 'var a; var b; eval a=1+(b=2); print a', '3'],
    [45, 'var a; var b; print a=1+(b=2)',         '3'],
    [46, 'def x {42}', ''],
    [47, 'def x {var x=42; x+1; print x}', '42'],
    [48, 'def x {a=1+(b=2); print a}', '3'],
    [49, 'def x {print a=1+(b=2)}',    '3'],
    [50, 'def x {print (a=1)+(b=2)}',  '3'],

    [51, '', '== input ==\n0000    1:1  RET', 'disasm'],
    [52, 'eval nil',
        '== input ==\n0000    1:9  NIL\n0001      |  POP\n0002      |  RET',
        'disasm'],
    [53, 'eval 42',
        "== input ==\n0000    1:8  CONST         0 '42'\n"
                     "0002      |  POP\n0003      |  RET",
        'disasm'],
    [54, 'def b {}',
        "== input ==\n0000    1:8  DEFBLOCK      0 'b'\t   1 ''\n"
                     "0003    1:9  ENDBLOCK\n0004      |  RET",
        'disasm'],
]

def perr(*args):
    print(*args, file=stderr)

def run_tests():
    cmd = './bcl'

    had_err = False
    for i, prog, exp in tests:
        try:
            res = subprocess.check_output(cmd.split(), input=prog, text=True)
            res = res.strip()
            if res != exp:
                had_err = True
                perr(f'#{i} mismatch: have {res!r}, want {exp!r}')

        except subprocess.CalledProcessError:
            perr(f'#{i} {cmd} error')
            had_err = True

    if had_err: exit(1)


def undot(s):
    return s.replace('.', '_')

def generate():
    with open('apigen_test.go', 'w') as f:
        print('// Code generated by "./test.py generate"; DO NOT EDIT.', file=f)
        print('\npackage bcl', file=f)
        for (i, inp, outp, *opt) in tests:
            print(f'\nfunc Example_i{undot(str(i))}() {{', file=f)
            if 'disasm' in opt:
                print(f'\tInterpret([]byte(`{inp}`), OptDisasm(true))', file=f)
            else:
                print(f'\tInterpret([]byte(`{inp}`))', file=f)
            print('\t// Output:', file=f)
            for line in outp.split('\n'):
                if line: print('\t//', line, file=f)
            print('}', file=f)


if __name__ == '__main__':
    from sys import argv as args
    if len(args)>1 and args[1] == 'generate':
        generate()
    else:
        run_tests()
