#!/usr/bin/env python3

import subprocess
from sys import stderr, exit

tests = [
    [ 0, 'eval "expr that is discarded"', ''],
    [ 1, 'var a; print not a', 'true'],
    [ 2, 'var a; print a==nil', 'true'],
    [ 3, 'var a=1; eval a=nil; print a==nil', 'true'],
    [ 4, 'print 1+1', '2'],
    [ 5, 'print 1+2.14', '3.14'],
    [ 6, 'print 123/2-50+2*8', '27'],
    [ 7, 'print 1-2', '-1'],
    [ 8, 'print 1--2', '3'],
    [ 9, 'print 1- +1', '0'],
    [10, 'print 1+ +1', '2'],
    [11, 'print ---10', '-10'],
    [12, 'print not 1>3', 'true'],
    [13, 'print 1<2 and 0 or "whatever"', '0'],
    [14, 'print 1>2 or true and 42', '42'],
    [15, 'print 1<10/5 and 127*-1+154', '27'],
    [16, 'print "q"*2', 'qq'],
    [17, 'print "q"+"x"', 'qx'],
    [18, 'print "q"+3', 'q3'],
    [19, 'print "q"+3.14', 'q3.14'],
    [20, 'var a=100; var b=a-90; print -b', '-10'],
    [21, 'var a=1; var b=2; print a+b',  '3'],
    [22, 'var a=1; eval a=a+1; print a', '2'],
    [23, 'var a=1; print a=a+1',         '2'],
    [24, 'def blk {print TYPE}',         'blk'],
    [25, 'def blk "foo" {print TYPE+"."+NAME}', 'blk.foo'],
    [26, 'var a=1; def blk {print TYPE}',   'blk'],
    [27, 'print 1; def blk {print TYPE}',   '1\nblk'],
    [28, 'var a=1; def blk {print TYPE+a}', 'blk1'],
    [29, 'def blk {var a=1; print TYPE+a}', 'blk1'],
    [30, 'var x=1; def blk {var a=1+x; print TYPE+a}',   'blk2'],
    [31, 'def blk {var a=1; var b=2; print TYPE+(a+b)}', 'blk3'],
    [32, 'var x=5; def blk {var a=1; var b=2; print TYPE+(a+b+x)}', 'blk8'],
    [33, 'def b1{var x=1; def b2 {var a=2; print TYPE+(a+x)}}',     'b23'],
    [34, 'var a=5; def blk {var a=a+1; print TYPE+a}',   'blk6'],
    [35, 'def b1{var a=5; def b2 {var a=a+1; print TYPE+a} print TYPE+a}', 'b26\nb15'],
    [36, 'def b1{var a=5; def b2 {eval a=a+1; print TYPE+a} print TYPE+a}','b26\nb16'],
    [37, 'def b1{ print TYPE; def b2{print TYPE} }; def b3{print TYPE}', 'b1\nb2\nb3'],
    [38, 'var a; var b; eval a=1+(b=2); print a', '3'],
    [39, 'var a; var b; print a=1+(b=2)',         '3'],
    [40, 'def x {42}', ''],
    [41, 'def x {var x=42; x+1; print x}', '42'],
    [42, 'def x {a=1+(b=2); print a}', '3'],
    [43, 'def x {print a=1+(b=2)}',    '3'],
]

def perr(*args):
    print(*args, file=stderr)

def run_tests():
    cmd = './bcl'

    had_err = False
    for i, prog, exp in tests:
        try:
            res = subprocess.check_output(cmd.split(), input=prog, text=True)
            res = res.strip()
            if res != exp:
                had_err = True
                perr(f'#{i} mismatch: have {res!r}, want {exp!r}')

        except subprocess.CalledProcessError:
            perr(f'#{i} {cmd} error')
            had_err = True

    if had_err: exit(1)


def generate():
    with open('apigen_test.go', 'w') as f:
        print('// Code generated by "./test.py generate"; DO NOT EDIT.', file=f)
        print('\npackage bcl', file=f)
        for (i, inp, outp) in tests:
            print(f'\nfunc Example_i{i}() {{', file=f)
            print(f'\tInterpret([]byte(`{inp}`))', file=f)
            print('\t// Output:', file=f)
            for line in outp.split('\n'):
                if line: print('\t//', line, file=f)
            print('}', file=f)


if __name__ == '__main__':
    from sys import argv as args
    if len(args)>1 and args[1] == 'generate':
        generate()
    else:
        run_tests()
