// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package bcl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tFAIL-0]
	_ = x[tEOF-1]
	_ = x[tERR-2]
	_ = x[tINT-3]
	_ = x[tFLOAT-4]
	_ = x[tSTR-5]
	_ = x[tIDENT-6]
	_ = x[tVAR-7]
	_ = x[tDEF-8]
	_ = x[tEVAL-9]
	_ = x[tPRINT-10]
	_ = x[tBIND-11]
	_ = x[tTRUE-12]
	_ = x[tFALSE-13]
	_ = x[tNIL-14]
	_ = x[tEQ-15]
	_ = x[tLCURLY-16]
	_ = x[tRCURLY-17]
	_ = x[tLPAREN-18]
	_ = x[tRPAREN-19]
	_ = x[tOR-20]
	_ = x[tAND-21]
	_ = x[tNOT-22]
	_ = x[tEE-23]
	_ = x[tBE-24]
	_ = x[tLT-25]
	_ = x[tLE-26]
	_ = x[tGT-27]
	_ = x[tGE-28]
	_ = x[tPLUS-29]
	_ = x[tMINUS-30]
	_ = x[tSTAR-31]
	_ = x[tSLASH-32]
	_ = x[tCOLON-33]
	_ = x[tARROW-34]
	_ = x[tSEMICOLON-35]
	_ = x[tMAX-36]
}

const _tokenType_name = "tFAILtEOFtERRtINTtFLOATtSTRtIDENTtVARtDEFtEVALtPRINTtBINDtTRUEtFALSEtNILtEQtLCURLYtRCURLYtLPARENtRPARENtORtANDtNOTtEEtBEtLTtLEtGTtGEtPLUStMINUStSTARtSLASHtCOLONtARROWtSEMICOLONtMAX"

var _tokenType_index = [...]uint8{0, 5, 9, 13, 17, 23, 27, 33, 37, 41, 46, 52, 57, 62, 68, 72, 75, 82, 89, 96, 103, 106, 110, 114, 117, 120, 123, 126, 129, 132, 137, 143, 148, 154, 160, 166, 176, 180}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
