// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package bcl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tFAIL-0]
	_ = x[tEOF-1]
	_ = x[tERR-2]
	_ = x[tINT-3]
	_ = x[tFLOAT-4]
	_ = x[tSTR-5]
	_ = x[tIDENT-6]
	_ = x[tVAR-7]
	_ = x[tDEF-8]
	_ = x[tEVAL-9]
	_ = x[tPRINT-10]
	_ = x[tTRUE-11]
	_ = x[tFALSE-12]
	_ = x[tNIL-13]
	_ = x[tEQ-14]
	_ = x[tLCURLY-15]
	_ = x[tRCURLY-16]
	_ = x[tLPAREN-17]
	_ = x[tRPAREN-18]
	_ = x[tOR-19]
	_ = x[tAND-20]
	_ = x[tNOT-21]
	_ = x[tEE-22]
	_ = x[tBE-23]
	_ = x[tLT-24]
	_ = x[tLE-25]
	_ = x[tGT-26]
	_ = x[tGE-27]
	_ = x[tPLUS-28]
	_ = x[tMINUS-29]
	_ = x[tSTAR-30]
	_ = x[tSLASH-31]
	_ = x[tSEMICOLON-32]
	_ = x[tMAX-33]
}

const _tokenType_name = "tFAILtEOFtERRtINTtFLOATtSTRtIDENTtVARtDEFtEVALtPRINTtTRUEtFALSEtNILtEQtLCURLYtRCURLYtLPARENtRPARENtORtANDtNOTtEEtBEtLTtLEtGTtGEtPLUStMINUStSTARtSLASHtSEMICOLONtMAX"

var _tokenType_index = [...]uint8{0, 5, 9, 13, 17, 23, 27, 33, 37, 41, 46, 52, 57, 63, 67, 70, 77, 84, 91, 98, 101, 105, 109, 112, 115, 118, 121, 124, 127, 132, 138, 143, 149, 159, 163}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
