// Code generated by "stringer -type typecode -trimprefix type"; DO NOT EDIT.

package bcl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[typeNIL-0]
	_ = x[typeINT-1]
	_ = x[typeFLOAT-2]
	_ = x[typeSTR-3]
	_ = x[typeBOOL-4]
}

const _typecode_name = "NILINTFLOATSTRBOOL"

var _typecode_index = [...]uint8{0, 3, 6, 11, 14, 18}

func (i typecode) String() string {
	if i >= typecode(len(_typecode_index)-1) {
		return "typecode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _typecode_name[_typecode_index[i]:_typecode_index[i+1]]
}
