name: Go

on:
  push:
    branches: [ master, exp ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - run: go build -v ./...

    - run: go test -coverprofile=coverage.out ./...

    - run: go test -race .

    - uses: jandelgado/gcov2lcov-action@v1
    - uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
